In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('Global_Superstore2.csv', encoding='latin1')

In [4]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,19-06-2014,19-06-2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.01,Medium
51286,35398,US-2014-102288,20-06-2014,24-06-2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.01,Medium
51287,40470,US-2013-155768,02-12-2013,02-12-2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.01,High
51288,9596,MX-2012-140767,18-02-2012,22-02-2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.00,Medium
51289,6147,MX-2012-134460,22-05-2012,26-05-2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.00,High

In [5]:
df.shape

(51290, 24)

In [6]:
df.info

<bound method DataFrame.info of        Row ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       32298   CA-2012-124891  31-07-2012  31-07-2012        Same Day
1       26341    IN-2013-77878  05-02-2013  07-02-2013    Second Class
2       25330    IN-2013-71249  17-10-2013  18-10-2013     First Class
3       13524  ES-2013-1579342  28-01-2013  30-01-2013     First Class
4       47221     SG-2013-4320  05-11-2013  06-11-2013        Same Day
...       ...              ...         ...         ...             ...
51285   29002    IN-2014-62366  19-06-2014  19-06-2014        Same Day
51286   35398   US-2014-102288  20-06-2014  24-06-2014  Standard Class
51287   40470   US-2013-155768  02-12-2013  02-12-2013        Same Day
51288    9596   MX-2012-140767  18-02-2012  22-02-2012  Standard Class
51289    6147   MX-2012-134460  22-05-2012  26-05-2012    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845         933.57        Critical
1          0.1 -288.7650         923.63        Critical
2          0.1  919.9710         915.49          Medium
3          0.1  -96.5400         910.16          Medium
4          0.0  311.5200         903.04        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000           0.01          Medium
51286      0.8   -1.1100           0.01          Medium
51287      0.0   11.2308           0.01            High
51288      0.0    2.4000           0.00          Medium
51289      0.0    1.8000           0.00            High

[51290 rows x 24 columns]>

In [7]:
df.describe

<bound method NDFrame.describe of        Row ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       32298   CA-2012-124891  31-07-2012  31-07-2012        Same Day
1       26341    IN-2013-77878  05-02-2013  07-02-2013    Second Class
2       25330    IN-2013-71249  17-10-2013  18-10-2013     First Class
3       13524  ES-2013-1579342  28-01-2013  30-01-2013     First Class
4       47221     SG-2013-4320  05-11-2013  06-11-2013        Same Day
...       ...              ...         ...         ...             ...
51285   29002    IN-2014-62366  19-06-2014  19-06-2014        Same Day
51286   35398   US-2014-102288  20-06-2014  24-06-2014  Standard Class
51287   40470   US-2013-155768  02-12-2013  02-12-2013        Same Day
51288    9596   MX-2012-140767  18-02-2012  22-02-2012  Standard Class
51289    6147   MX-2012-134460  22-05-2012  26-05-2012    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845         933.57        Critical
1          0.1 -288.7650         923.63        Critical
2          0.1  919.9710         915.49          Medium
3          0.1  -96.5400         910.16          Medium
4          0.0  311.5200         903.04        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000           0.01          Medium
51286      0.8   -1.1100           0.01          Medium
51287      0.0   11.2308           0.01            High
51288      0.0    2.4000           0.00          Medium
51289      0.0    1.8000           0.00            High

[51290 rows x 24 columns]>

In [8]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [9]:
df.drop([ 'Postal Code' ],axis=1, inplace = True)

In [10]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
City              0
State             0
Country           0
Market            0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Cost     0
Order Priority    0
dtype: int64

In [11]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Market', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Cost', 'Order Priority'],
      dtype='object')

In [12]:
df.columns = df.columns.str.lower()

In [14]:
df.columns =  df.columns.str.replace(' ','_')

In [15]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'city', 'state', 'country',
       'market', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'quantity', 'discount', 'profit',
       'shipping_cost', 'order_priority'],
      dtype='object')

In [21]:
df.head(10 )

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,product_id,category,sub-category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2012-86369,14-04-2012,18-04-2012,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40155,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850,867.69,Low
9,40936,CA-2012-116638,28-01-2012,31-01-2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical

In [24]:
df_sorted = df.sort_values(by="row_id", ascending=True)

In [25]:
df_sorted

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,product_id,category,sub-category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority
46162,1,MX-2014-143658,02-10-2014,06-10-2014,Standard Class,SC-20575,Sonia Cooley,Consumer,Mexico City,Distrito Federal,...,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium
19159,2,MX-2012-155047,15-10-2012,20-10-2012,Standard Class,KW-16570,Kelly Williams,Consumer,Dos Quebradas,Risaralda,...,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium
23056,3,MX-2012-155047,15-10-2012,20-10-2012,Standard Class,KW-16570,Kelly Williams,Consumer,Dos Quebradas,Risaralda,...,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium
44210,4,MX-2012-155047,15-10-2012,20-10-2012,Standard Class,KW-16570,Kelly Williams,Consumer,Dos Quebradas,Risaralda,...,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium
34383,5,MX-2012-155047,15-10-2012,20-10-2012,Standard Class,KW-16570,Kelly Williams,Consumer,Dos Quebradas,Risaralda,...,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41249,51286,HU-2012-7730,05-09-2012,07-09-2012,First Class,NF-8385,Natalie Fritzler,Consumer,Budapest,Budapest,...,OFF-AVE-10004570,Office Supplies,Binders,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High
19511,51287,HU-2012-7730,05-09-2012,07-09-2012,First Class,NF-8385,Natalie Fritzler,Consumer,Budapest,Budapest,...,TEC-LOG-10004419,Technology,Accessories,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High
24154,51288,HU-2012-7730,05-09-2012,07-09-2012,First Class,NF-8385,Natalie Fritzler,Consumer,Budapest,Budapest,...,OFF-BOS-10002705,Office Supplies,Art,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High
15417,51289,HU-2012-7730,05-09-2012,07-09-2012,First Class,NF-8385,Natalie Fritzler,Consumer,Budapest,Budapest,...,OFF-ENE-10004132,Office Supplies,Paper,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High
39355,51290,IZ-2011-5750,25-08-2011,29-08-2011,Standard Class,SZ-10035,Sam Zeldin,Home Office,Baghdad,Baghdad,...,OFF-ACC-10002343,Office Supplies,Binders,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium

In [26]:
df .duplicated().sum()

np.int64(0)

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
row_id,51290.0,25645.500000,14806.291990,1.000,12823.250000,25645.500,38467.7500,51290.000
sales,51290.0,246.490581,487.565361,0.444,30.758625,85.053,251.0532,22638.480
quantity,51290.0,3.476545,2.278766,1.000,2.000000,3.000,5.0000,14.000
discount,51290.0,0.142908,0.212280,0.000,0.000000,0.000,0.2000,0.850
profit,51290.0,28.610982,174.340972,-6599.978,0.000000,9.240,36.8100,8399.976
shipping_cost,51290.0,26.375915,57.296804,0.000,2.610000,7.790,24.4500,933.570

In [30]:
df.groupby ('category') ['sales'].mean()

category
Furniture          416.248905
Office Supplies    121.097120
Technology         467.858939
Name: sales, dtype: float64

In [34]:
df.groupby('category')['profit'].mean().round(2)

category
Furniture          28.88
Office Supplies    16.58
Technology         65.45
Name: profit, dtype: float64

In [35]:
df['category'].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [36]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\vikas prajapati\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\vikas prajapati\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\vikas prajapati\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vikas prajapati\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
from sqlalchemy import create_engine
import pandas as pd 
# MySQL connection
username = "root"
password = "vikas9140"
host = "localhost"
port = "3306"
database = "Global_superstore2"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "superstore"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,product_id,category,sub-category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical